apiVersion: v1
kind: Service
metadata:
  name: {{ include "eugo-docint.fullname" . }}
  labels:
    {{- include "eugo-docint.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "eugo-docint.selectorLabels" . | nindent 4 }}
