{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eugo-docint.serviceAccountName" . }}
  labels:
    {{- include "eugo-docint.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.azureClientId }}
  annotations:
    azure.workload.identity/client-id: {{ . | quote }}
  {{- end }}
{{- end }}
